#ifdef DAMIAO_CONFIGURE_Hs
#define DAMIAO_CONFIGURE_H

#define DM_YAW_3_ANGLE_MAX 0.45
#define DM_YAW_3_ANGLE_MIN -3.0

#define DM_PITCH_2_ANGLE_MAX 3.0
#define DM_PITCH_2_ANGLE_MIN -3.0

#define DM_ROLL_1_ANGLE_MAX 1.7
#define DM_ROLL_1_ANGLE_MIN -1.7

#endif